# Copyright 2021, Proofcraft Pty Ltd
#
# SPDX-License-Identifier: BSD-2-Clause

name: 'microkit/Hardware Runs'
description: |
  Does microkit test runs from previously built images for all hardware test platforms.
author: Julia Vassiliki <julia.vassiliki@unsw.edu.au>

inputs:
  platform:
    description: Comma separated list of hardware platforms to run the test for.
    required: true
  index:
    description: job index in matrix build
    required: true
  action_name:
    description: 'internal -- do not use'
    required: false
    default: 'microkit-hw-run'

runs:
  using: 'node24'
  main: '../js/index.js'
  post: '../js/post.js'
